name: apple_music_cover_art
description: A lightweight library to fetch music album cover art from the Apple Music API.
version: 1.0.1
repository: https://github.com/dgigantino/apple_music_cover_art.dart

environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.3.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
